elasticsearch:
  image: frosner/ddq-demo-elasticsearch:1.0.0
  expose:
    - "9200"
logstash:
  image: frosner/ddq-demo-logstash:1.0.0
  links:
    - elasticsearch
  expose:
    - "5044"
kibana:
  image: frosner/ddq-demo-kibana:1.0.0
  links:
    - elasticsearch
  ports:
    - 5601:5601
spark:
  image: frosner/ddq-demo-spark:1.0.0
  ports:
    - 4040:4040
  links:
    - datagenerator
    - logstash
datagenerator:
  image: frosner/ddq-demo-datagenerator:1.0.0
  expose:
    - "9999"
