elasticsearch:
  image: frosner/ddq-demo-elasticsearch
  expose:
    - "9200"
logstash:
  image: frosner/ddq-demo-logstash
  links:
    - elasticsearch
  expose:
    - "5044"
kibana:
  image: frosner/ddq-demo-kibana
  links:
    - elasticsearch
  ports:
    - "5601"
spark:
  image: frosner/ddq-demo-spark
  links:
    - datagenerator
datagenerator:
  image: frosner/ddq-demo-datagenerator
  expose:
    - "9999"
